const { CLIENT_EVENT_TYPES } = require('../config/constants');
const { isValidTimeZone } = require('./timeZone');

// Unicode-aware so names like "José" or "Zoë" are accepted.
const NAME_PATTERN = /^\p{L}[\p{L}\p{M}\s.'-]*$/u;
const CITY_PATTERN = /^\p{L}[\p{L}\p{M}\s.,'-]*$/u;
const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;
// Optional leading +, then 8–15 digits (E.164 max is 15). Covers bare
// national numbers (9876543210) and full numbers with country code (919876543210).
const PHONE_PATTERN = /^\+?\d{8,15}$/;
const CONTROL_CHARS = /[\u0000-\u001F\u007F]/;
// Anonymous IDs generated by the landing page (UUIDs or similar)
const ID_PATTERN = /^[A-Za-z0-9_-]{8,64}$/;

const isPlainObject = value =>
  value !== null && typeof value === 'object' && !Array.isArray(value);

const isBlank = value =>
  value === undefined || value === null || (typeof value === 'string' && value.trim() === '');

// Trims and collapses repeated whitespace: "  Rahul   Kumar " -> "Rahul Kumar"
const clean = value => value.trim().replace(/\s+/g, ' ');

function checkText(value, { label, min, max, pattern, patternMessage }) {
  if (isBlank(value)) return { error: `${label} is required` };
  if (typeof value !== 'string') return { error: `${label} must be text` };
  const text = clean(value);
  if (text.length < min || text.length > max) {
    return { error: `${label} must be between ${min} and ${max} characters` };
  }
  if (CONTROL_CHARS.test(text)) return { error: `${label} contains invalid characters` };
  if (pattern && !pattern.test(text)) return { error: patternMessage };
  return { value: text };
}

function checkPhone(value) {
  if (isBlank(value)) return { error: 'Phone number is required' };
  if (typeof value !== 'string' && typeof value !== 'number') {
    return { error: 'Invalid phone number' };
  }
  // Allow common formatting such as "+91 98765-43210" or "(987) 654 3210"
  const phone = String(value).trim().replace(/[\s().-]/g, '');
  if (!PHONE_PATTERN.test(phone)) return { error: 'Invalid phone number' };
  return { value: phone };
}

function checkEmail(value) {
  if (isBlank(value)) return { value: null }; // optional
  if (typeof value !== 'string') return { error: 'Invalid email address' };
  const email = value.trim().toLowerCase();
  if (email.length > 254 || !EMAIL_PATTERN.test(email)) {
    return { error: 'Invalid email address' };
  }
  return { value: email };
}

// --- Optional tracking fields: invalid values are dropped, never rejected,
// so a tracking problem can't block someone from registering. ---

const optionalId = value => (typeof value === 'string' && ID_PATTERN.test(value) ? value : null);

function optionalSourceTag(value) {
  if (typeof value !== 'string') return null;
  const tag = value.trim().toLowerCase().replace(/[^a-z0-9._-]/g, '').slice(0, 50);
  return tag || null;
}

// "https://site.com/landing?x=1" or "/landing" -> "/landing"
function pagePath(value) {
  if (typeof value !== 'string' || !value) return '/';
  let path = value;
  try {
    path = new URL(value, 'http://placeholder.local').pathname;
  } catch {
    return '/';
  }
  return path.startsWith('/') ? path.slice(0, 200) : '/';
}

/**
 * Validates a registration payload.
 * Only known fields are copied into `value`, so clients can't set id, status, etc.
 * @returns {{ value?: object, errors?: Record<string, string> }}
 */
function validateRegistration(body) {
  const input = isPlainObject(body) ? body : {};
  const result = collect({
    name: checkText(input.name, {
      label: 'Name', min: 2, max: 80, pattern: NAME_PATTERN,
      patternMessage: 'Name can only contain letters, spaces, dots, apostrophes and hyphens'
    }),
    phone: checkPhone(input.phone),
    email: checkEmail(input.email),
    city: checkText(input.city, {
      label: 'City', min: 2, max: 60, pattern: CITY_PATTERN,
      patternMessage: 'City can only contain letters, spaces, dots, commas, apostrophes and hyphens'
    }),
    course: checkText(input.course, { label: 'Course', min: 2, max: 100 })
  });
  if (result.errors) return result;

  return {
    value: {
      ...result.value,
      sessionId: optionalId(input.session_id),
      // Same ID on a repeated submit (e.g. double-click) = same registration
      submissionId: optionalId(input.submission_id),
      utmSource: optionalSourceTag(input.utm_source),
      gclid: Boolean(input.gclid),
      page: pagePath(input.page_url)
    }
  };
}

/** Validates a tracking event sent by the landing page (POST /api/track). */
function validateTrackEvent(body) {
  const input = isPlainObject(body) ? body : {};
  const errors = {};

  const sessionId = optionalId(input.session_id);
  if (!sessionId) errors.session_id = 'A valid session_id is required';
  if (!CLIENT_EVENT_TYPES.includes(input.event_type)) {
    errors.event_type = `event_type must be one of: ${CLIENT_EVENT_TYPES.join(', ')}`;
  }
  if (Object.keys(errors).length) return { errors };

  return {
    value: {
      sessionId,
      eventType: input.event_type,
      page: pagePath(input.page),
      utmSource: optionalSourceTag(input.utm_source),
      gclid: Boolean(input.gclid),
      referrer: typeof input.referrer === 'string' ? input.referrer.slice(0, 500) : ''
    }
  };
}

/**
 * Validates dashboard / report filters from the query string:
 * from, to (ISO dates), tz (IANA time zone), course, city, source
 */
function validateReportQuery(query) {
  const input = isPlainObject(query) ? query : {};
  const value = {};
  const errors = {};

  for (const key of ['from', 'to']) {
    if (isBlank(input[key])) continue;
    const time = typeof input[key] === 'string' ? Date.parse(input[key]) : NaN;
    if (Number.isNaN(time)) errors[key] = `${key} must be a date, e.g. 2026-09-28T00:00:00Z`;
    else value[key] = new Date(time).toISOString();
  }
  if (value.from && value.to && value.from > value.to) errors.to = 'to must be after from';

  if (!isBlank(input.tz)) {
    if (typeof input.tz === 'string' && isValidTimeZone(input.tz)) value.tz = input.tz;
    else errors.tz = 'tz must be a time zone such as Asia/Kolkata';
  }

  for (const key of ['course', 'city', 'source']) {
    if (isBlank(input[key])) continue;
    if (typeof input[key] === 'string' && input[key].length <= 100) value[key] = clean(input[key]);
    else errors[key] = `${key} must be text up to 100 characters`;
  }

  return Object.keys(errors).length ? { errors } : { value };
}

function collect(checks) {
  const value = {};
  const errors = {};
  for (const [field, result] of Object.entries(checks)) {
    if (result.error) errors[field] = result.error;
    else value[field] = result.value;
  }
  return Object.keys(errors).length ? { errors } : { value };
}

module.exports = {
  validateRegistration,
  validateTrackEvent,
  validateReportQuery
};
